GEN_COEFFS =       "tools/gen_coeffs.py"
PRECOMP_COEFFS =   "test/precomputed.pickle"
PRECOMP_ADJ_MAT =  "test/ico55_adj.pickle"
PRECOMP_ADJ_LIST = "test/ico55_list.pickle"
PRECOMP_CLUSTER =  "test/ico55.pickle"
